### ISSUE TITLE
LCD Keypad buttons misbehaving

### ISSUE THREAD

**Issue by scoutstang** [OpenAstroTech/OpenAstroTracker#40]
I just wanted to report an issue I ran into getting my new OAT build up and running. With the electronics hooked up and the latest firmware loaded, some of my buttons were misbehaving. Both the Left and Select buttons were acting like Select and the Down button was acting like Left.  

I was able to enable LCD_BUTTON_TEST in Globals.hpp to see the output of my buttons and then change the cutoff values accordingly in the checkKey () part of Utility.hpp. I changed the cutoffs to 50/300/500/700/950. Now the buttons respond correctly.

For the record, I am using firmware 1.7.04 with a Mega 2560 clone (Sunfounder) and the DFRobot LCD Kaypad Shield v1.1. They key diagnostic is reporting: 0-Right, 205-Up, 405-Down, 623-Left, 824-Select, and 1023-None.

Looking forward to clear skies so I can try it out soon!

**Comment by andre-stefanov** [comment]
Thanks for that information. We are indeed seeing this issues from time to time because the LCD Keypad shields seem to differ in terms of voltages on each button. Our proposed fix is exactly what you did. I will add this information to the wiki so maybe someone can look it up if he faces same problem.
